andznakan_tvyalner = '/html/body/div[1]/div[2]/div/div/div/div/div[4]/div/div/div[6]/div[1]'
next = '/html/body/div[1]/div[2]/div/div/div/div/div[4]/div/div/div[6]/div[2]/div/div/table/tbody/tr/td/div/div[2]/div[2]'
oragir = '/html/body/div[1]/div[2]/div/div/div/div/div[4]/div/div/div[6]/div[2]/div/div/div[2]/div/div[4]/div[1]/div[1]/div[1]/div/div/div/div[2]/div[2]/div[2]/div/div/div/div/div[3]/h4/strong/img'
artaqin_ughegrum = '/html/body/div[1]/div[2]/div/div/div/div/div[4]/div/div/div[6]/div[2]/div/div/div[2]/div/div[4]/div[1]/div[1]/div[1]/div/div/div/div[2]/div[2]/div[2]/div/div/div/div/div[3]/div[1]/a[1]'
bujhastatutyun = '/html/body/div[1]/div[2]/div/div/div/div/div[4]/div/div/div[6]/div[2]/div/div/div[2]/div/div[4]/div[1]/div[1]/div[1]/div/div/div/div[2]/div[2]/div[2]/div/div/div/div/div[3]/div[2]/div/div/div[2]/div[1]/div/div[1]/div[2]/div/input[1]'
nataly_pharm = '//*[@id="body"]/div[38]/div[2]/div'
nataly_test = '/html/body/div[37]/div[2]/div'
ughordman_tip ='/html/body/div[1]/div[2]/div/div/div/div/div[4]/div/div/div[6]/div[2]/div/div/div[2]/div/div[4]/div[1]/div[1]/div[1]/div/div/div/div[2]/div[2]/div[2]/div/div/div/div/div[3]/div[2]/div/div/div[2]/div[1]/div/div[1]/div[5]/span[1]/div/input[1]'
laborator_gorciqayin = '//*[@id="body"]/div[41]/div[2]/div'
laborator_gorciqayin_test = '/html/body/div[40]/div[2]/div'
nmusharman_npatak = '/html/body/div[1]/div[2]/div/div/div/div/div[4]/div/div/div[6]/div[2]/div/div/div[2]/div/div[4]/div[1]/div[1]/div[1]/div/div/div/div[2]/div[2]/div[2]/div/div/div/div/div[3]/div[2]/div/div/div[2]/div[1]/div/div[1]/div[5]/span[2]/div/input[1]'
ayl = '/html/body/div[46]/div[2]'
ayl_test = '/html/body/div[47]/div[2]/div'
teghakayum = '/html/body/div[1]/div[2]/div/div/div/div/div[4]/div/div/div[6]/div[2]/div/div/div[2]/div/div[4]/div[1]/div[1]/div[1]/div/div/div/div[2]/div[2]/div[2]/div/div/div/div/div[3]/div[2]/div/div/div[2]/div[1]/div/div[1]/div[5]/em/img'
ptichka_test = '/html/body/div[50]/div[2]/div/div/div[2]/div/div[2]/div[4]/div/label/input'
ptichka = '/html/body/div[51]/div[2]/div/div/div[2]/div/div[2]/div[4]/div/label'
manualy = '//*[@id="edit_id"]'
location = '#id617c39511bd82 > ymaps'
map_test = '/html/body/div[1]/div[2]/div/div/div/div/div[4]/div/div/div[6]/div[2]/div/div/div[2]/div/div[4]/div[1]/div[1]/div[1]/div/div/div/div[2]/div[2]/div[2]/div/div/div/div/div[3]/div[2]/div/div/div[2]/div[1]/div/div[1]/div[5]/em/img'
location_hastatel = '#body > div.ui-dialog.ui-corner-all.ui-widget.ui-widget-content.ui-front.ui-dialog-buttons.popup_eh > div.ui-dialog-buttonpane.ui-widget-content.ui-helper-clearfix > div > button.index_1.ui-button.ui-corner-all.ui-widget'
location_2 = '/html/body/div[50]/div[3]/div/button[2]'
carayutyun = '/html/body/div[1]/div[2]/div/div/div/div/div[4]/div/div/div[6]/div[2]/div/div/div[2]/div/div[4]/div[1]/div[1]/div[1]/div/div/div/div[2]/div[2]/div[2]/div/div/div/div/div[3]/div[2]/div/div/div[2]/div[1]/div/div[1]/div[8]/div[2]/div[2]/div/input[1]'
rnt_haytnaberum = '/html/body/div[43]/div[2]/div'
rnt_2 = '//*[@id="body"]/div[42]/div[2]/div'
finaly_hishel = '/html/body/div[1]/div[2]/div/div/div/div/div[4]/div/div/div[6]/div[2]/div/div/div[2]/div/div[4]/div[1]/div[1]/div[1]/div/div/div/div[2]/div[2]/div[2]/div/div/div/div/div[3]/div[2]/div/div[1]/div[2]/div[3]/div[3]/input[1]'
finaly_ok = '/html/body/div[37]/div[3]/div'
finaly_ok_2 = '//*[@id="body"]/div[38]/div[3]/div'
ayceri_avart = '/html/body/div[1]/div[2]/div/div/div/ul/li[5]/div[2]'
name_redactor = '/html/body/div[1]/div[2]/div/div/div/div/div[4]/div/div/div[1]/div[2]/div[1]/div[1]/div/div[1]/div[2]/div[1]/div/span[5]/span/em[2]'
name_field = '/html/body/div[1]/div[2]/div/div/div/div/div[4]/div/div/div[1]/div[2]/div[1]/div[1]/div/div[1]/div[2]/div[1]/div/span[5]/input'
name_save = '/html/body/div[1]/div[2]/div/div/div/div/div[4]/div/div/div[1]/div[2]/div[1]/div[1]/div/div[1]/div[2]/div[1]/div/span[5]/span/em[1]'
surname_redactor ='/html/body/div[1]/div[2]/div/div/div/div/div[4]/div/div/div[1]/div[2]/div[1]/div[1]/div/div[1]/div[2]/div[1]/div/span[6]/span/em[2]'
surname_field ='/html/body/div[1]/div[2]/div/div/div/div/div[4]/div/div/div[1]/div[2]/div[1]/div[1]/div/div[1]/div[2]/div[1]/div/span[6]/input'
surname_save ='/html/body/div[1]/div[2]/div/div/div/div/div[4]/div/div/div[1]/div[2]/div[1]/div[1]/div/div[1]/div[2]/div[1]/div/span[6]/span/em[1]'
phone_redactor = '/html/body/div[1]/div[2]/div/div/div/div/div[4]/div/div/div[1]/div[2]/div[1]/div[1]/div/div[1]/div[2]/div[1]/div/span[7]/span/em[2]'
phone_field = '/html/body/div[1]/div[2]/div/div/div/div/div[4]/div/div/div[1]/div[2]/div[1]/div[1]/div/div[1]/div[2]/div[1]/div/span[7]/input'
phone_save = '/html/body/div[1]/div[2]/div/div/div/div/div[4]/div/div/div[1]/div[2]/div[1]/div[1]/div/div[1]/div[2]/div[1]/div/span[7]/span/em[1]'
name_path = '/html/body/div[1]/div[2]/div/div/div/div/div[4]/div/div/div[1]/div[2]/div[1]/div[1]/div/div[1]/div[2]/div[1]/div/span[5]'
surname_path = '/html/body/div[1]/div[2]/div/div/div/div/div[4]/div/div/div[1]/div[2]/div[1]/div[1]/div/div[1]/div[2]/div[1]/div/span[6]'
phone_path = '/html/body/div[1]/div[2]/div/div/div/div/div[4]/div/div/div[1]/div[2]/div[1]/div[1]/div/div[1]/div[2]/div[1]/div/span[7]'
depqi_tesak = '/html/body/div[1]/div[2]/div/div/div/div/div[4]/div/div/div[2]/div[2]/div/div/div/div[1]/table[1]/tbody/tr/td/div/div'
ambulator = '/html/body/div[14]/div[2]/div[1]'
inqnamekusacum_ok = '/html/body/div[22]/div[3]/div/button'
npatak = '//*[@id="visit_edit_div_hwapp_app_main_div_14_accardion_patientdataeditable_encounter"]/div/div'
hivandutyun = '//*[@id="body"]/div[11]/div[2]/div[1]'
depqi_hamar = '/html/body/div[1]/div[2]/div/div/div/div/div[4]/div/div/div[2]/div[2]/div/div/div/div[1]/table[2]/tbody/tr/td/input'
finans_aghbyur = '/html/body/div[1]/div[2]/div/div/div/div/div[4]/div/div/div[2]/div[2]/div/div/div/div[1]/table[7]/tbody/tr/td/div/div'
vcharovi = '//*[@id="body"]/div[12]/div[2]/div[1]'
akhtoroshum = '/html/body/div[1]/div[2]/div/div/div/div/div[4]/div/div/div[4]/div[1]/div[2]/a[2]'
bjishkner = '/html/body/div[1]/div[2]/div/div/div/div/div[4]/div/div/div[5]/div[1]/div[2]/a[2]'
ughekcox = '/html/body/div[1]/div[2]/div/div/div/div/div[4]/div/div/div[4]/div[2]/div[1]/div[1]/div/div/div[2]/input[2]'
covid_field = '/html/body/div[1]/div[2]/div/div/div/div/div[4]/div/div/div[4]/div[2]/div[1]/div[2]/div/div/span[1]/div/input[1]'
corona = '//*[@id="body"]/div[24]/div[2]'
covid_hastatum = '/html/body/div[1]/div[2]/div/div/div/div/div[4]/div/div/div[4]/div[2]/div[1]/div[2]/div/span/input[1]'
covid_ok ='/html/body/div[25]/div[3]/div/button'
cheghyal = '/html/body/div[1]/div[2]/div/div/div/div/div[4]/div/div/div[4]/div[2]/div[1]/div[2]/div/span/input[2]'
arka = '/html/body/div[1]/div[2]/div/div/div/div/div[4]/div/div/div[4]/div[2]/div[1]/div[1]/div/div/div[2]/input[1]'
arka_corona ='/html/body/div[1]/div[2]/div/div/div/div/div[4]/div/div/div[4]/div[2]/div[1]/div[2]/div/div/span/span/div/input[1]'
corona_click ='/html/body/div[1]/div[2]/div/div/div/div/div[4]/div/div/div[4]/div[2]/div[1]/div[2]/div/span/input[1]'
add_doctor = '/html/body/div[1]/div[2]/div/div/div/div/div[4]/div/div/div[5]/div[2]/div[1]/div[1]/div/div/div[2]/input[2]'
doctor_field = '/html/body/div[1]/div[2]/div/div/div/div/div[4]/div/div/div[5]/div[2]/div[1]/div[2]/div/div/div[2]/span/input[1]'
doctor ='//*[@id="_easyui_tree_42"]/span[4]'
doctor_hastatum ='/html/body/div[1]/div[2]/div/div/div/div/div[4]/div/div/div[5]/div[2]/div[1]/div[2]/div/span/input[1]'
add_patient = '/html/body/div[1]/div[2]/div/div/div/div/div[1]/div/div[1]/div[2]/div[2]/img'
info_field = '/html/body/div[1]/div[2]/div/div/div/div/div[4]/div/div/div[1]/div[2]/div[1]/div[1]/div/div[1]/div[2]/div[2]/span/input[1]'
patients = '/html/body/div[18]/div[1]'
patients_test = '/html/body/div[23]/div[1]' #/html/body/div[8]/div[1]/div
patients_test2 ='/html/body/div[23]/div[1]/div/div'
patient_id = '/html/body/div[1]/div[2]/div/div/div/div/div[4]/div/div/div[1]/div[2]/div[1]/div[1]/div/div[1]/div[2]/div[1]/div/span[3]'
aycer = '//*[@id="lelem_n2"]/div[1]/div[1]'
password = '/html/body/div/div[2]/div/div/div[2]/div[2]/div/form/div/div[3]/div[2]/input'
identify_code = '/html/body/div/div[2]/div/div/div[2]/div[2]/div/form/div/div[3]/div[3]/input'
login = '//*[@id="login_password_form"]/div[6]/input'
next1= '//*[@id="default_login_div"]/div[4]/div/input'
login_field = '/html/body/div/div[2]/div/div/div[2]/div[2]/div/form/div/div[1]/div/div[1]/div[2]/input[1]'
partq_ok = '#body > div.ui-dialog.ui-corner-all.ui-widget.ui-widget-content.ui-front.ui-dialog-buttons.ui-draggable.popup_eh > div.ui-dialog-buttonpane.ui-widget-content.ui-helper-clearfix > div > button'
place_field = '/html/body/div[51]/div[2]/div/div/div[2]/div/div[1]/div[3]/div/div/input'
place_field_2 = '//*[@id="id61817db59d8aa"]'
